# Generated by Django 4.2.5 on 2025-02-01 04:01

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('order', '0004_remove_orderitem_price_remove_orderitem_product_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PromotionCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('promotion_code', models.CharField(max_length=7, unique=True, verbose_name='プロモーションコード')),
                ('discount_amount', models.DecimalField(decimal_places=0, max_digits=5, validators=[django.core.validators.MinValueValidator(100), django.core.validators.MaxValueValidator(1000)], verbose_name='割引額')),
                ('is_used_promotion_code', models.BooleanField(default=False, verbose_name='プロモーションコード使用済みフラグ')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='プロモーションコード作成日時')),
                ('used_at', models.DateTimeField(blank=True, null=True, verbose_name='プロモーションコード使用日時')),
                ('order_used_promotion_code', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='used_promotion_code', to='order.order', verbose_name='プロモーションコードが使用された注文')),
            ],
            options={
                'db_table': 'promotion_code',
                'indexes': [models.Index(fields=['promotion_code'], name='promotion_c_promoti_1c9e48_idx'), models.Index(fields=['is_used_promotion_code'], name='promotion_c_is_used_f451dd_idx')],
            },
        ),
    ]
