# Generated by Django 4.2.5 on 2025-02-01 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('promotion', '0001_initial'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='promotioncode',
            name='promotion_c_is_used_f451dd_idx',
        ),
        migrations.RenameField(
            model_name='promotioncode',
            old_name='is_used_promotion_code',
            new_name='is_used',
        ),
        migrations.RemoveField(
            model_name='promotioncode',
            name='order_used_promotion_code',
        ),
        migrations.AddIndex(
            model_name='promotioncode',
            index=models.Index(fields=['is_used'], name='promotion_c_is_used_b730fd_idx'),
        ),
    ]
