# Generated by Django 4.2.5 on 2025-01-25 12:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='paymentinfo',
            old_name='save_info',
            new_name='payment_save_info',
        ),
    ]
