# Generated by Django 4.2.5 on 2025-02-02 08:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('promotion', '0002_remove_promotioncode_promotion_c_is_used_f451dd_idx_and_more'),
        ('order', '0005_order_final_price_order_promotion_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='promotion_code',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='promotion.promotioncode'),
        ),
    ]
